language: php

php:
  - '7.1'

before_script:
  - cp .env.example .env
  - composer self-update
  - composer install --dev --prefer-source --no-interaction
  - php artisan key:generate

addons:
  sonarcloud:
    organization: "elinenube" 
    token:
      secure: "SONAR_TOKEN"


script:
  - ./vendor/bin/phpunit --configuration ./phpunit.xml
  - sonar-scanner